### PR TITLE
Fix and update css

### PR DESCRIPTION
**Pull request by emorri08**
fixes link to stylesheet and adds a few more styles to application

### CODE REVIEW

**Comment by emorri08** [comment]
I think this is the step I skipped. Let me know if this resolves the issue.

**Comment by thomaskise** [comment]
This looks good now.  I did change the name of the merge requst.  You add
"Add files via upload". I changed to " Fix and update css"

--Thom

**Comment by emorri08** [comment]
Sounds good! I'll be back on my laptop in a minute. Is there anything else
that I need to do?

Great teamwork, guys! =)

**Comment by emorri08** [comment]
Ick I think I did the reply instead of reply all again. I need to work on
that one. I actually think it's part of the reason I was let go from my
summer job a week before I intended to give notice.

**Comment by thomaskise** [comment]
No, I did it. You're good.

**Review by thomaskise — COMMENTED** [review]
I like your updates to the css! This looks good. I'll do the merge now.

**Pull request merged**
